### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by kallaspriit** [Factor-Robotics/odrive_ros2_control#1]
Hey, seems to be a nice library, trying to use it to control a differential drive robot but not entirely sure how to use it.

Managed to compile it and launch it with

`os2 launch odrive_bringup odrive.launch.py enable_joint1:=true`

Also managed to subscribe to the joint states topic.

`ros2 topic echo /dynamic_joint_states`

How would I go about controlling the motor velocities etc? Some documentation about using the library and some examples would help the package :)

**Comment by borongyuan** [comment]
Hi,

sorry for the missing document. We will add more examples and instructions after various tests.

The current launch file use velocity controllers by default. Of course you need enable_joint1 if you want to use both joints. The three basic controllers (position, velocity, effort) are inherited from forward_command_controller. They accept std_msgs/Float64MultiArray as input. You can try following command to set velocity of joint0.
```
ros2 topic pub -r 100 /joint0_velocity_controller/commands std_msgs/Float64MultiArray "layout:
  dim:
  - label: ''
    size: 1
    stride: 1
  data_offset: 0
data: [1]"
```
For differential drive robot, a better solution is to use [diff_drive_controller](https://github.com/ros-controls/ros2_controllers/tree/master/diff_drive_controller). This controller handles two joints using velocity interface. It subscribes cmd_vel and publishes odometry. Please refer to DiffBot in [ros2_control_demos](https://github.com/ros-controls/ros2_control_demos) for configurations.
